[package]
name = "root-reader"
version = "0.1.0"
authors = ["Hajime Fukuda <haji.fkd@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1"
thiserror = "1.0"
flate2 = "1.0"